### ISSUE TITLE
RuntimeError: The size of tensor a (20) must match the size of tensor b (25) at non-singleton dimension 1

### ISSUE THREAD

**Issue by dbl001** [TropComplique/lda2vec-pytorch#12]
I am getting this error running lda2vec-pytorch on Google's CoLab platorm on a text file with 5,171 news articles from global websites.
E.g. 
RuntimeError: The size of tensor a (20) must match the size of tensor b (25) at non-singleton dimension 1

from lda2vec_loss.py:
print(doc_weights.shape, doc_probs.shape, unsqueezed_doc_probs.shape, unsqueezed_topic_vectors.shape)

torch.Size([7168, 20]) torch.Size([7168, 20]) torch.Size([7168, 20, 1]) torch.Size([1, 25, 50])

```
%run get_stories_windows.ipynb
100%|██████████| 5171/5171 [22:09<00:00,  1.36it/s]
number of removed short documents: 5
total number of tokens: 5841072
number of tokens to be removed: 2660533
number of additionally removed short documents: 3
total number of tokens: 3180503

minimum word count number: 18
this number can be less than MIN_COUNTS because of document removal
5163it [00:08, 616.10it/s]
CPU times: user 1h 23min 15s, sys: 2.38 s, total: 1h 23min 18s
Wall time: 42min 10s
  2%|▏         | 108/5163 [00:00<00:04, 1074.25it/s]CPU times: user 12.1 s, sys: 7.26 s, total: 19.3 s
Wall time: 9.84 s
topic 0 : Point Vladimir Union Moscow progress migration air Mosul Insight safe
topic 1 : Hong Morocco Kong les sur Jamaica Carnoustie Escocia Park Turkish
topic 2 : Got Talent Baron Sacha Club UAE AMERICA SHOWTIME Trapeze talent
topic 3 : Kentucky Lil Peoria Song Minnesota CBS hai Cyclone boy KZN
topic 4 : Game NBA Oman heat Tokyo Utah Bangla Soccer Basketball Mail
topic 5 : Ganga Chennai Bengaluru Hyderabad ordeal Theatre thREAD CLOSE Sabha Mumbai
topic 6 : Army syrian AGT Philippines Syrian Baltimore February October army January
topic 7 : ADVERTISEMENT Deutsch Programs migrant teach Podcasts turkish Puigdemont XXL Reuters
topic 8 : Air Force NYC Iraq Turkmenistan Kazakhstan Nordic Energy CBS Affairs
topic 9 : Philadelphia Mix Pennsylvania Route Baltimore Episode Summer Deep Massachusetts Park
topic 10 : Herald ZEALAND NEW IOL NZME Property crash Northern Pakuranga serial
topic 11 : RFI GMT Paris attachment Mon gmt Fri flash bulletin analysis
topic 12 : Nairobi Counties Rift switch Ethiopia NTV hoursÂ Ruaraka Eritrea Gold
topic 13 : Texas Russian Oman Newscasts Image Star Fry summer funny Vermont
topic 14 : Premium Content Zuckerberg Conference arab Gaza jewish JPost Careers Diaspora
topic 15 : Messenger WhatsApp external LinkedIn Queen window Prince Kilmeade School Elizabeth
topic 16 : Director Documentary London Chicago Game Tower Urdu Airlines english Egypt
topic 17 : Peninsula EBITDA Khmer Hungary SPAIN amazing thai Partners khmer lottery
topic 18 : Amsterdam Mark Fox Amazon Swansea Song Qatar TIME Indonesia durationStr
topic 19 : Pak Headlines pak modi india England pakistani Reaction indian Pakistani
100%|██████████| 5163/5163 [00:05<00:00, 977.59it/s]

!python train.py

number of documents: 5163
number of windows: 3180503
number of topics: 25
vocabulary size: 19224
word embedding dim: 50
../utils/lda2vec_loss.py:47: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.doc_weights.weight, std=DOC_WEIGHTS_INIT)
number of batches: 444 

epoch 1
  0% 0/444 [00:00<?, ?it/s]../utils/lda2vec_loss.py:196: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  doc_probs = F.softmax(doc_weights)
torch.Size([7168, 20]) torch.Size([7168, 20]) torch.Size([7168, 20, 1]) torch.Size([1, 25, 50])

Traceback (most recent call last):
  File "train.py", line 36, in <module>
    main()
  File "train.py", line 32, in main
    save_every=20, grad_clip=5.0
  File "../utils/training.py", line 127, in train
    neg_loss, dirichlet_loss = model(doc_indices, pivot_words, target_words)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../utils/lda2vec_loss.py", line 70, in forward
    doc_vectors = self.topics(doc_weights)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../utils/lda2vec_loss.py", line 208, in forward
    doc_vectors = (unsqueezed_doc_probs*unsqueezed_topic_vectors).sum(1)
RuntimeError: The size of tensor a (20) must match the size of tensor b (25) at non-singleton dimension 1
```

Pytorch version issue?  Perhaps:

https://github.com/marvis/pytorch-yolo2/issues/106

but in any case, the shapes don't match up:
e.g. 
torch.Size([7168, 20, 1]) torch.Size([1, 25, 50])

**Comment by dbl001** [comment]
n_topics in get_windows.ipynb (for lda):
E.g. - 
n_topics = 25
must equal n_topis in train.py.
(Otherwise, doc_weights_init.npy shape will be mismatched with the self.doc_weights Embedding tensor in lda2vec_loss.py).
