### ISSUE TITLE
RuntimeError: invalid argument 1: must be >= 0 and <= 1 at /pytorch/aten/src/TH/THRandom.cpp:320

### ISSUE THREAD

**Issue by dbl001** [TropComplique/lda2vec-pytorch#13]
This exception is happening training 20newgroups with the embed_dimension 300 in GoogleColab with pytorch 1.1.0 with cuda 10.
Curiously, it does not happen training on my Mac with only the CPU.

From alias_multinomial.py:

```
    def draw(self, N):
        """Draw N samples from the distribution."""

        K = self.J.size(0)
        r = torch.LongTensor(np.random.randint(0, K, size=N))
        q = self.q.index_select(0, r)
        j = self.J.index_select(0, r)
        b = torch.bernoulli(q)
        #print("K r q j b r.shape, q.shape j.shape b.shape, j.shape", K, r, q, j, b, r.shape, q.shape, j.shape, b.shape, j.shape)
        oq = r.mul(b.long())
        oj = j.mul((1 - b).long())
        return oq + oj

Traceback (most recent call last):
  File "train.py", line 36, in <module>
    main()
  File "train.py", line 32, in main
    save_every=20, grad_clip=5.0
  File "../utils/training.py", line 127, in train
    neg_loss, dirichlet_loss = model(doc_indices, pivot_words, target_words)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../utils/lda2vec_loss.py", line 82, in forward
    neg_loss = self.neg(pivot_words, target_words, doc_vectors, w)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../utils/lda2vec_loss.py", line 152, in forward
    noise = self.multinomial.draw(batch_size*window_size*self.num_sampled)
  File "../utils/alias_multinomial.py", line 60, in draw
    b = torch.bernoulli(q)
RuntimeError: invalid argument 1: must be >= 0 and <= 1 at /pytorch/aten/src/TH/THRandom.cpp:320
```
q.min() and q.max()
0.21869047
1.0066459

This seems relevant:

https://github.com/pytorch/pytorch/issues/9917

**Comment by dbl001** [comment]
Try this: 
```
self.q = torch.clamp(self.q, 0.0, 1.0)
self.J = torch.clamp(self.J, 0, K- 1)
```
instead of this:
```
self.q.clamp(0.0, 1.0)
self.J.clamp(0, K - 1)
```
