### ISSUE TITLE
run failed in get_windows.ipynb

### ISSUE THREAD

**Issue by DongShanHu** [TropComplique/lda2vec-pytorch#8]
_call__() got an unexpected keyword argument 'tag'

i have the problem in 
 encoded_docs, decoder, word_counts = preprocess(
    docs, nlp, MIN_LENGTH, MIN_COUNTS, MAX_COUNTS
)
i don't know why i have this problem

**Comment by DongShanHu** [comment]
i skip the paremeter tag and parse in preprocess.py and run it success
but, while i run the step2   train.py
i  have the problem about cuda  like this 
number of documents: 13109
number of windows: 1063444
number of topics: 25
vocabulary size: 7596
word embedding dim: 50
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=30 : unknown error
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    main()
  File "train.py", line 32, in main
    save_every=20, grad_clip=5.0
  File "../utils/training.py", line 72, in train
    weights = torch.FloatTensor(weights).cuda()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:74

how i can solve it?  tks

**Comment by avinashok** [comment]
Did you get answer for the second question @DongShanHu ? Do you know how to solve the "cuda" issue with the code @TropComplique ?
